import {
	ExpectedContractType,
	ExpectedTypeWork,
	IStudentData,
} from './src/types/IStudentData';
export const dummyStudents: IStudentData[] = [
	{
		bio: 'Pasjonat programowania z doświadczeniem w JavaScript.',
		bonusProjectUrls: ['https://projekt1.com', 'https://projekt2.com'],
		canTakeApprenticeship: true,
		courseCompletion: 4.5,
		courseEngagement: 4,
		courses: 'Frontend Development',
		education: 'Informatyka, Uniwersytet Warszawski',
		email: 'jan.kowalski@example.com',
		expectedContractType: ExpectedContractType.B2B,
		expectedSalary: 8000,
		expectedTypeWork: ExpectedTypeWork.REMOTE,
		firstName: 'Jan',
		githubUsername: 'janKowalski',
		id: 'student-1',
		lastName: 'Kowalski',
		monthsOfCommercialExp: 12,
		portfolioUrls: ['https://portfolio1.com'],
		projectUrls: ['https://projekt1.com'],
		projectDegree: 5,
		targetWorkCity: 'Warszawa',
		teamProjectDegree: 4,
		phone: '123-456-789',
		workExperience: '1 rok jako Frontend Developer',
	},
	{
		bio: 'Programistka z zamiłowaniem do danych i analizy.',
		bonusProjectUrls: [],
		canTakeApprenticeship: false,
		courseCompletion: 5,
		courseEngagement: 5,
		courses: 'Data Science',
		education: 'Matematyka stosowana, Politechnika Wrocławska',
		email: 'anna.nowak@example.com',
		expectedContractType: ExpectedContractType.UoP,
		expectedSalary: 10000,
		expectedTypeWork: ExpectedTypeWork.AT_LOCATION,
		firstName: 'Anna',
		githubUsername: 'annaNowak',
		id: 'student-2',
		lastName: 'Nowak',
		monthsOfCommercialExp: 6,
		portfolioUrls: null,
		projectUrls: ['https://data-projekt1.com'],
		projectDegree: 4.5,
		targetWorkCity: 'Wrocław',
		teamProjectDegree: 4.5,
		phone: '987-654-321',
		workExperience: '6 miesięcy jako Junior Data Analyst',
	},
	{
		bio: 'Specjalista od backendu z doświadczeniem w Node.js.',
		bonusProjectUrls: ['https://backend-projekt.com'],
		canTakeApprenticeship: true,
		courseCompletion: 4,
		courseEngagement: 4.5,
		courses: 'Backend Development',
		education: null,
		email: 'tomasz.zielinski@example.com',
		expectedContractType: ExpectedContractType.IRRELEVANT,
		expectedSalary: null,
		expectedTypeWork: ExpectedTypeWork.HYBRID,
		firstName: 'Tomasz',
		githubUsername: 'tomekZielinski',
		id: 'student-3',
		lastName: 'Zieliński',
		monthsOfCommercialExp: 18,
		portfolioUrls: ['https://backend-portfolio.com'],
		projectUrls: [
			'https://backend-projekt1.com',
			'https://backend-projekt2.com',
		],
		projectDegree: 4.2,
		targetWorkCity: 'Kraków',
		teamProjectDegree: 4,
		phone: '555-333-222',
		workExperience: '18 miesięcy jako Backend Developer',
	},
	{
		bio: 'Specjalista od backendu z doświadczeniem w Node.js.',
		bonusProjectUrls: ['https://backend-projekt.com'],
		canTakeApprenticeship: true,
		courseCompletion: 4,
		courseEngagement: 4.5,
		courses: 'Backend Development',
		education: null,
		email: 'tomasz.zielinski@example.com',
		expectedContractType: ExpectedContractType.IRRELEVANT,
		expectedSalary: null,
		expectedTypeWork: ExpectedTypeWork.HYBRID,
		firstName: 'Tomasz',
		githubUsername: 'tomekZielinski',
		id: 'student-4',
		lastName: 'Zieliński',
		monthsOfCommercialExp: 18,
		portfolioUrls: ['https://backend-portfolio.com'],
		projectUrls: [
			'https://backend-projekt1.com',
			'https://backend-projekt2.com',
		],
		projectDegree: 4.2,
		targetWorkCity: 'Kraków',
		teamProjectDegree: 4,
		phone: '555-333-222',
		workExperience: '18 miesięcy jako Backend Developer',
	},
	{
		bio: 'Specjalista od backendu z doświadczeniem w Node.js.',
		bonusProjectUrls: ['https://backend-projekt.com'],
		canTakeApprenticeship: true,
		courseCompletion: 4,
		courseEngagement: 4.5,
		courses: 'Backend Development',
		education: null,
		email: 'tomasz.zielinski@example.com',
		expectedContractType: ExpectedContractType.IRRELEVANT,
		expectedSalary: null,
		expectedTypeWork: ExpectedTypeWork.HYBRID,
		firstName: 'Tomasz',
		githubUsername: 'tomekZielinski',
		id: 'student-5',
		lastName: 'Zieliński',
		monthsOfCommercialExp: 18,
		portfolioUrls: ['https://backend-portfolio.com'],
		projectUrls: [
			'https://backend-projekt1.com',
			'https://backend-projekt2.com',
		],
		projectDegree: 4.2,
		targetWorkCity: 'Kraków',
		teamProjectDegree: 4,
		phone: '555-333-222',
		workExperience: '18 miesięcy jako Backend Developer',
	},
	{
		bio: 'Specjalista od backendu z doświadczeniem w Node.js.',
		bonusProjectUrls: ['https://backend-projekt.com'],
		canTakeApprenticeship: true,
		courseCompletion: 4,
		courseEngagement: 4.5,
		courses: 'Backend Development',
		education: null,
		email: 'tomasz.zielinski@example.com',
		expectedContractType: ExpectedContractType.IRRELEVANT,
		expectedSalary: null,
		expectedTypeWork: ExpectedTypeWork.HYBRID,
		firstName: 'Tomasz',
		githubUsername: 'tomekZielinski',
		id: 'student-6',
		lastName: 'Zieliński',
		monthsOfCommercialExp: 18,
		portfolioUrls: ['https://backend-portfolio.com'],
		projectUrls: [
			'https://backend-projekt1.com',
			'https://backend-projekt2.com',
		],
		projectDegree: 4.2,
		targetWorkCity: 'Kraków',
		teamProjectDegree: 4,
		phone: '555-333-222',
		workExperience: '18 miesięcy jako Backend Developer',
	},
	{
		bio: 'Specjalista od backendu z doświadczeniem w Node.js.',
		bonusProjectUrls: ['https://backend-projekt.com'],
		canTakeApprenticeship: true,
		courseCompletion: 4,
		courseEngagement: 4.5,
		courses: 'Backend Development',
		education: null,
		email: 'tomasz.zielinski@example.com',
		expectedContractType: ExpectedContractType.IRRELEVANT,
		expectedSalary: null,
		expectedTypeWork: ExpectedTypeWork.HYBRID,
		firstName: 'Tomasz',
		githubUsername: 'tomekZielinski',
		id: 'student-7',
		lastName: 'Zieliński',
		monthsOfCommercialExp: 18,
		portfolioUrls: ['https://backend-portfolio.com'],
		projectUrls: [
			'https://backend-projekt1.com',
			'https://backend-projekt2.com',
		],
		projectDegree: 4.2,
		targetWorkCity: 'Kraków',
		teamProjectDegree: 4,
		phone: '555-333-222',
		workExperience: '18 miesięcy jako Backend Developer',
	},
	{
		bio: 'Specjalista od backendu z doświadczeniem w Node.js.',
		bonusProjectUrls: ['https://backend-projekt.com'],
		canTakeApprenticeship: true,
		courseCompletion: 4,
		courseEngagement: 4.5,
		courses: 'Backend Development',
		education: null,
		email: 'tomasz.zielinski@example.com',
		expectedContractType: ExpectedContractType.IRRELEVANT,
		expectedSalary: null,
		expectedTypeWork: ExpectedTypeWork.HYBRID,
		firstName: 'Tomasz',
		githubUsername: 'tomekZielinski',
		id: 'student-8',
		lastName: 'Zieliński',
		monthsOfCommercialExp: 18,
		portfolioUrls: ['https://backend-portfolio.com'],
		projectUrls: [
			'https://backend-projekt1.com',
			'https://backend-projekt2.com',
		],
		projectDegree: 4.2,
		targetWorkCity: 'Kraków',
		teamProjectDegree: 4,
		phone: '555-333-222',
		workExperience: '18 miesięcy jako Backend Developer',
	},
	{
		bio: 'Specjalista od backendu z doświadczeniem w Node.js.',
		bonusProjectUrls: ['https://backend-projekt.com'],
		canTakeApprenticeship: true,
		courseCompletion: 4,
		courseEngagement: 4.5,
		courses: 'Backend Development',
		education: null,
		email: 'tomasz.zielinski@example.com',
		expectedContractType: ExpectedContractType.IRRELEVANT,
		expectedSalary: null,
		expectedTypeWork: ExpectedTypeWork.HYBRID,
		firstName: 'Tomasz',
		githubUsername: 'tomekZielinski',
		id: 'student-9',
		lastName: 'Zieliński',
		monthsOfCommercialExp: 18,
		portfolioUrls: ['https://backend-portfolio.com'],
		projectUrls: [
			'https://backend-projekt1.com',
			'https://backend-projekt2.com',
		],
		projectDegree: 4.2,
		targetWorkCity: 'Kraków',
		teamProjectDegree: 4,
		phone: '555-333-222',
		workExperience: '18 miesięcy jako Backend Developer',
	},
	{
		bio: 'Specjalista od backendu z doświadczeniem w Node.js.',
		bonusProjectUrls: ['https://backend-projekt.com'],
		canTakeApprenticeship: true,
		courseCompletion: 4,
		courseEngagement: 4.5,
		courses: 'Backend Development',
		education: null,
		email: 'tomasz.zielinski@example.com',
		expectedContractType: ExpectedContractType.IRRELEVANT,
		expectedSalary: null,
		expectedTypeWork: ExpectedTypeWork.HYBRID,
		firstName: 'Tomasz',
		githubUsername: 'tomekZielinski',
		id: 'student-10',
		lastName: 'Zieliński',
		monthsOfCommercialExp: 18,
		portfolioUrls: ['https://backend-portfolio.com'],
		projectUrls: [
			'https://backend-projekt1.com',
			'https://backend-projekt2.com',
		],
		projectDegree: 4.2,
		targetWorkCity: 'Kraków',
		teamProjectDegree: 4,
		phone: '555-333-222',
		workExperience: '18 miesięcy jako Backend Developer',
	},
	{
		bio: 'Specjalista od backendu z doświadczeniem w Node.js.',
		bonusProjectUrls: ['https://backend-projekt.com'],
		canTakeApprenticeship: true,
		courseCompletion: 4,
		courseEngagement: 4.5,
		courses: 'Backend Development',
		education: null,
		email: 'tomasz.zielinski@example.com',
		expectedContractType: ExpectedContractType.IRRELEVANT,
		expectedSalary: null,
		expectedTypeWork: ExpectedTypeWork.HYBRID,
		firstName: 'Tomasz',
		githubUsername: 'tomekZielinski',
		id: 'student-11',
		lastName: 'Zieliński',
		monthsOfCommercialExp: 18,
		portfolioUrls: ['https://backend-portfolio.com'],
		projectUrls: [
			'https://backend-projekt1.com',
			'https://backend-projekt2.com',
		],
		projectDegree: 4.2,
		targetWorkCity: 'Kraków',
		teamProjectDegree: 4,
		phone: '555-333-222',
		workExperience: '18 miesięcy jako Backend Developer',
	},
	{
		bio: 'Specjalista od backendu z doświadczeniem w Node.js.',
		bonusProjectUrls: ['https://backend-projekt.com'],
		canTakeApprenticeship: true,
		courseCompletion: 4,
		courseEngagement: 4.5,
		courses: 'Backend Development',
		education: null,
		email: 'tomasz.zielinski@example.com',
		expectedContractType: ExpectedContractType.IRRELEVANT,
		expectedSalary: null,
		expectedTypeWork: ExpectedTypeWork.HYBRID,
		firstName: 'Tomasz',
		githubUsername: 'tomekZielinski',
		id: 'student-12',
		lastName: 'Zieliński',
		monthsOfCommercialExp: 18,
		portfolioUrls: ['https://backend-portfolio.com'],
		projectUrls: [
			'https://backend-projekt1.com',
			'https://backend-projekt2.com',
		],
		projectDegree: 4.2,
		targetWorkCity: 'Kraków',
		teamProjectDegree: 4,
		phone: '555-333-222',
		workExperience: '18 miesięcy jako Backend Developer',
	},
	{
		bio: 'Entuzjasta JavaScript i React z doświadczeniem w tworzeniu aplikacji webowych.',
		bonusProjectUrls: ['https://js-projekt.com'],
		canTakeApprenticeship: false,
		courseCompletion: 4,
		courseEngagement: 4.5,
		courses: 'Fullstack Development',
		education: 'Informatyka, Politechnika Poznańska',
		email: 'jakub.nowak@example.com',
		expectedContractType: ExpectedContractType.UoP,
		expectedSalary: 7000,
		expectedTypeWork: ExpectedTypeWork.HYBRID,
		firstName: 'Jakub',
		githubUsername: 'jakubNowak',
		id: 'student-13',
		lastName: 'Nowak',
		monthsOfCommercialExp: 10,
		portfolioUrls: ['https://jakub-portfolio.com'],
		projectUrls: ['https://fullstack-projekt1.com'],
		projectDegree: 3.8,
		targetWorkCity: 'Poznań',
		teamProjectDegree: 3.5,
		phone: '600-700-800',
		workExperience: '1 rok jako Junior Fullstack Developer',
	},
	{
		bio: 'Entuzjasta JavaScript i React z doświadczeniem w tworzeniu aplikacji webowych.',
		bonusProjectUrls: ['https://js-projekt.com'],
		canTakeApprenticeship: false,
		courseCompletion: 4,
		courseEngagement: 4.5,
		courses: 'Fullstack Development',
		education: 'Informatyka, Politechnika Poznańska',
		email: 'jakub.nowak@example.com',
		expectedContractType: ExpectedContractType.UoP,
		expectedSalary: 7000,
		expectedTypeWork: ExpectedTypeWork.HYBRID,
		firstName: 'Jakub',
		githubUsername: 'jakubNowak',
		id: 'student-14',
		lastName: 'Nowak',
		monthsOfCommercialExp: 10,
		portfolioUrls: ['https://jakub-portfolio.com'],
		projectUrls: ['https://fullstack-projekt1.com'],
		projectDegree: 3.8,
		targetWorkCity: 'Poznań',
		teamProjectDegree: 3.5,
		phone: '600-700-800',
		workExperience: '1 rok jako Junior Fullstack Developer',
	},
	{
		bio: 'Entuzjasta JavaScript i React z doświadczeniem w tworzeniu aplikacji webowych.',
		bonusProjectUrls: ['https://js-projekt.com'],
		canTakeApprenticeship: false,
		courseCompletion: 4,
		courseEngagement: 4.5,
		courses: 'Fullstack Development',
		education: 'Informatyka, Politechnika Poznańska',
		email: 'jakub.nowak@example.com',
		expectedContractType: ExpectedContractType.UoP,
		expectedSalary: 7000,
		expectedTypeWork: ExpectedTypeWork.HYBRID,
		firstName: 'Jakub',
		githubUsername: 'jakubNowak',
		id: 'student-15',
		lastName: 'Nowak',
		monthsOfCommercialExp: 10,
		portfolioUrls: ['https://jakub-portfolio.com'],
		projectUrls: ['https://fullstack-projekt1.com'],
		projectDegree: 3.8,
		targetWorkCity: 'Poznań',
		teamProjectDegree: 3.5,
		phone: '600-700-800',
		workExperience: '1 rok jako Junior Fullstack Developer',
	},
	{
		bio: 'Entuzjasta JavaScript i React z doświadczeniem w tworzeniu aplikacji webowych.',
		bonusProjectUrls: ['https://js-projekt.com'],
		canTakeApprenticeship: false,
		courseCompletion: 4,
		courseEngagement: 4.5,
		courses: 'Fullstack Development',
		education: 'Informatyka, Politechnika Poznańska',
		email: 'jakub.nowak@example.com',
		expectedContractType: ExpectedContractType.UoP,
		expectedSalary: 7000,
		expectedTypeWork: ExpectedTypeWork.HYBRID,
		firstName: 'Jakub',
		githubUsername: 'jakubNowak',
		id: 'student-16',
		lastName: 'Nowak',
		monthsOfCommercialExp: 10,
		portfolioUrls: ['https://jakub-portfolio.com'],
		projectUrls: ['https://fullstack-projekt1.com'],
		projectDegree: 3.8,
		targetWorkCity: 'Poznań',
		teamProjectDegree: 3.5,
		phone: '600-700-800',
		workExperience: '1 rok jako Junior Fullstack Developer',
	},
	{
		bio: 'Entuzjasta JavaScript i React z doświadczeniem w tworzeniu aplikacji webowych.',
		bonusProjectUrls: ['https://js-projekt.com'],
		canTakeApprenticeship: false,
		courseCompletion: 4,
		courseEngagement: 4.5,
		courses: 'Fullstack Development',
		education: 'Informatyka, Politechnika Poznańska',
		email: 'jakub.nowak@example.com',
		expectedContractType: ExpectedContractType.UoP,
		expectedSalary: 7000,
		expectedTypeWork: ExpectedTypeWork.HYBRID,
		firstName: 'Jakub',
		githubUsername: 'jakubNowak',
		id: 'student-17',
		lastName: 'Nowak',
		monthsOfCommercialExp: 10,
		portfolioUrls: ['https://jakub-portfolio.com'],
		projectUrls: ['https://fullstack-projekt1.com'],
		projectDegree: 3.8,
		targetWorkCity: 'Poznań',
		teamProjectDegree: 3.5,
		phone: '600-700-800',
		workExperience: '1 rok jako Junior Fullstack Developer',
	},
	{
		bio: 'Entuzjasta JavaScript i React z doświadczeniem w tworzeniu aplikacji webowych.',
		bonusProjectUrls: ['https://js-projekt.com'],
		canTakeApprenticeship: false,
		courseCompletion: 4,
		courseEngagement: 4.5,
		courses: 'Fullstack Development',
		education: 'Informatyka, Politechnika Poznańska',
		email: 'jakub.nowak@example.com',
		expectedContractType: ExpectedContractType.UoP,
		expectedSalary: 7000,
		expectedTypeWork: ExpectedTypeWork.HYBRID,
		firstName: 'Jakub',
		githubUsername: 'jakubNowak',
		id: 'student-18',
		lastName: 'Nowak',
		monthsOfCommercialExp: 10,
		portfolioUrls: ['https://jakub-portfolio.com'],
		projectUrls: ['https://fullstack-projekt1.com'],
		projectDegree: 3.8,
		targetWorkCity: 'Poznań',
		teamProjectDegree: 3.5,
		phone: '600-700-800',
		workExperience: '1 rok jako Junior Fullstack Developer',
	},
	{
		bio: 'Entuzjasta JavaScript i React z doświadczeniem w tworzeniu aplikacji webowych.',
		bonusProjectUrls: ['https://js-projekt.com'],
		canTakeApprenticeship: false,
		courseCompletion: 4,
		courseEngagement: 4.5,
		courses: 'Fullstack Development',
		education: 'Informatyka, Politechnika Poznańska',
		email: 'jakub.nowak@example.com',
		expectedContractType: ExpectedContractType.UoP,
		expectedSalary: 7000,
		expectedTypeWork: ExpectedTypeWork.HYBRID,
		firstName: 'Jakub',
		githubUsername: 'jakubNowak',
		id: 'student-19',
		lastName: 'Nowak',
		monthsOfCommercialExp: 10,
		portfolioUrls: ['https://jakub-portfolio.com'],
		projectUrls: ['https://fullstack-projekt1.com'],
		projectDegree: 3.8,
		targetWorkCity: 'Poznań',
		teamProjectDegree: 3.5,
		phone: '600-700-800',
		workExperience: '1 rok jako Junior Fullstack Developer',
	},
	{
		bio: 'Entuzjasta JavaScript i React z doświadczeniem w tworzeniu aplikacji webowych.',
		bonusProjectUrls: ['https://js-projekt.com'],
		canTakeApprenticeship: false,
		courseCompletion: 4,
		courseEngagement: 4.5,
		courses: 'Fullstack Development',
		education: 'Informatyka, Politechnika Poznańska',
		email: 'jakub.nowak@example.com',
		expectedContractType: ExpectedContractType.UoP,
		expectedSalary: 7000,
		expectedTypeWork: ExpectedTypeWork.HYBRID,
		firstName: 'Jakub',
		githubUsername: 'jakubNowak',
		id: 'student-20',
		lastName: 'Nowak',
		monthsOfCommercialExp: 10,
		portfolioUrls: ['https://jakub-portfolio.com'],
		projectUrls: ['https://fullstack-projekt1.com'],
		projectDegree: 3.8,
		targetWorkCity: 'Poznań',
		teamProjectDegree: 3.5,
		phone: '600-700-800',
		workExperience: '1 rok jako Junior Fullstack Developer',
	},
];
